# Generated by Django 2.2.25 on 2022-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField(blank=True, default=None, max_length=500, null=True, verbose_name='url')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('test', 'test'), ('dev', 'dev')], default='test', max_length=10, null=True)),
            ],
        ),
    ]
